### ISSUE TITLE
simulation crushes

### ISSUE THREAD

**Issue by Abbode** [Qucs/qucsator#28]
hello everyone , I made a simple circuit as to try qucs , I used what I learnt in the docs , yet NO SIMULATION would run at all .
this is the netlist : 

R:R1 Vout _net0 R="50 Ohm" Temp="26.85" Tc1="0.0" Tc2="0.0" Tnom="26.85"
R:R2 gnd Vout R="50 Ohm" Temp="26.85" Tc1="0.0" Tc2="0.0" Tnom="26.85"
Vdc:V1 _net0 gnd U="1 V"
.DC:DC1 Temp="26.85" reltol="0.001" abstol="1 pA" vntol="1 uV" saveOPs="no" MaxIter="150" saveAll="no" convHelper="none" Solver="CroutLU"

this is the log file : 

[log.txt](https://github.com/Qucs/qucs/files/6352949/log.txt)

I'm using QUCS 0.0.19 on fedora workstation 33 with GNOME UI , I installed qucs from official repos .

thanks are in advance..

EDIT: not even the examples shipped with qucs by default would run simulation .

**Comment by felix-salfelder** [comment]
> I'm almost certain it will work on fedora.

hah. I am no longer so sure after #29. Please try 0.0.20, either way. Reopen if you find anything new.
