### ISSUE TITLE
Assertion in stl_vector.h:1123 on Fedora 28

### ISSUE THREAD

**Issue by KavalchukD** [Qucs/qucsator#37]
Simulating any circuit leads to a failed assertion on Fedora 28 and the version of the project from Fedora rep qucs-0.0.20~rc2-3.fc38.x86_64 
Assertion string looks like:
/usr/include/c++/13/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = qucs::nodelist_t*; _Alloc = std::allocator<qucs::nodelist_t*>; reference = qucs::nodelist_t*&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
The picture of the circuit:
![image](https://github.com/Qucs/qucs/assets/39777281/334dcad4-fa35-4cf6-b013-646b8749d149)
It seems it is the same issue as the following https://github.com/rstudio/httpuv/issues/133.
Here is a fix https://github.com/rstudio/httpuv/commit/6cf767fbb6b981aa44ce8f6970feca9a773ed42e.

Since there is no trace and only logs, it is quite tricky to determine the exact line where undefined behaviour happened. Here is the log though:
[log.txt](https://github.com/Qucs/qucs/files/11492306/log.txt)
Please, do not hesitate to contact me if you need any help with gathering additional info or even debugging the program.

**Comment by felix-salfelder** [comment]
On Tue, May 16, 2023 at 02:50:54PM -0700, Dzmitry Kavalchuk wrote:
> Simulating any circuit leads to a failed assertion on Fedora 28 and the version of the project from Fedora rep qucs-0.0.20~rc2-3.fc38.x86_64 
> Assertion string looks like:
> /usr/include/c++/13/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = qucs::nodelist_t*; _Alloc = std::allocator<qucs::nodelist_t*>; reference = qucs::nodelist_t*&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
> The picture of the circuit:
> ![image](https://github.com/Qucs/qucs/assets/39777281/334dcad4-fa35-4cf6-b013-646b8749d149)
> It seems it is the same issue as the following https://github.com/rstudio/httpuv/issues/133.
> Here is a fix https://github.com/rstudio/httpuv/commit/6cf767fbb6b981aa44ce8f6970feca9a773ed42e.
> 
> Since there is no trace and only logs, it is quite tricky to determine the exact line where undefined behaviour happened. Here is the log though:
> [log.txt](https://github.com/Qucs/qucs/files/11492306/log.txt)
> Please, do not hesitate to contact me if you need any help with gathering additional info or even debugging the program.

Hi Dzmitry.

At least one bug of this kind has been fixed in qucsator/develop (after
the 0.0.20 release). Please check if the problem still exists there.

thanks
felix

**Comment by KavalchukD** [comment]
Hey Felix!
Sure. I should admit I've faced some issues while building the project locally. I had decided to use cmake + ninja, and qucsator file didn't seem to run. It hung for at least several minutes as far as I checked.

**Comment by KavalchukD** [comment]
Running bootstrap to generate configure causes 
sh bootstrap
bootstrapping the qucs-core sources...
Creating aclocal.m4... bootstrap: line 33: aclocal: command not found
Here are those lines:
echo -n "Creating aclocal.m4... "
${ACLOCAL:-aclocal} -I m4 || exit 1

**Comment by KavalchukD** [comment]
It seems I failed to recognise the structure of this project. I built a correct project which is of course qucs itself, and the object of the issue is seems fixed on the actual revision. 
![image](https://github.com/Qucs/qucsator/assets/39777281/db00e009-065f-455f-9b66-53eb20e9feae)
Thank you, Felix.

**Comment by schnittchen** [comment]
Nice to learn that the issue I just bumped into as a new user seems to be fixed, but I'm not going to build a QT Project from sources...

**Comment by felix-salfelder** [comment]
On Sun, Feb 16, 2025 at 05:37:27AM -0800, Schnittchen wrote:
> Nice to learn that the issue I just bumped into as a new user seems to
> be fixed,

You are welcome.

There hasn't been much interest in Qucsator lately. For further
development or a release, we'd need to find a maintainer.

Not much else to see here. If you only need binaries for Fedora, ask
them to supply a patched version.

> but I'm not going to build a QT Project from sources...

What makes you believe that Qucsator is a "QT Project"? If there is an
error in the documentation, please point it out in a new ticket.
